language: r
cache: packages

r_packages:
  - covr

addons:
  apt:
    sources:
      - sourceline: 'ppa:cran/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - gdal-bin 
      - libgdal-dev 
      - libgdal1-dev 
      - netcdf-bin 
      - libproj-dev 
      - libnetcdf-dev 
      - netcdf-bin

after_success:
  - Rscript -e 'covr::codecov()'

compiler:
  - clang

warnings_are_errors: false

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: GXkm1WAyjhaG5VSHCZNHlUylQKt8ZsRtwAXmYyZr4B11eVtCWtYQw+O/fTmAeu8R/IwgTCJnDpqcmCBb+jz5uC6eJv3aXdAxalN0+G7IU/y005KdAowz12G3u13rMlnw0KYHe0tWh8IusycMZWY0xh927IylOJndTn+0hpCEEmg=
